### ISSUE TITLE
Wrong XML tag matched and replaced

### ISSUE THREAD

**Issue by step-** [andymass/vim-matchup#48]
Using vim-matchup commit e3016e0
vim 8.1

```vim
let g:loaded_matchit = 1 " near the top of ~/.vim/vimrc
...
Plug 'andymass/vim-matchup' " install with vim-plug
...
" plugin vim-matchup {{{1
"To enable the experimental transmute module
let g:matchup_transmute_enabled = 1
"Deferred highlighting improves cursor movement performance
let g:matchup_matchparen_deferred = 1
```
### Explain the issue

For the attached XML file, which consistently reproduces the problem on my system:
1. `:set ft=xml` `:syn on` then put the curson on line 6, which is blank.
2. Note that the `<checkbox>` tag on lines 7-12 is properly closing. We're going to show that either `<checkbox>` or `</checkbox>` are incorrectly changed to another tag when deleting a blank line.
3. Delete blank line 6. This puts the cursor on line 7 (now 6) and highlights `<checkbox>` as well as `</checkbox>` on line 12 (now 11). I'm going to use new line numbers now.
4. Press j to move to blank line 12
5. Delete line 12.
6. Note that `</checkbox>` has turned into `</label>`. Alternatively, note that `<checkbox>` has turned into `<text>`. In either case, it seems that vim-matchup is tricked into matching one of the tags of line 14.

Note: the attached file comes from a real project - it's a valid `gtkdialog` specification.
[vim-matchup-20181230.xml.txt](https://github.com/andymass/vim-matchup/files/2717593/vim-matchup-20181230.xml.txt)

**Comment by andymass** [comment]
Thank you for the very clear description; reproduced.  46f411c1d936a38b7bbe2a1e0dce51329facf6cc should fix it.

In retrospect, auto-transmute is quite dangerous because in some cases it is impossible to know what the desired change was.  I am considering adding a mapping to trigger it instead.

**Comment by step-** [comment]
I agree, it can be dangerous. Still, I find it useful and will continue to use it.
> in some cases it is impossible to know what the desired change was
Could the plugin identify such cases? If so it could prompt for directions or hold the change with a warning.

**Comment by step-** [comment]
Unfortunately this issue still happens with different XML test input.
```xml

        <variable>x</variable>
        
        <action>a ''</action>

```
which is
```
00000000: 0a20 2020 2020 2020 203c 7661 7269 6162  .        <variab
00000010: 6c65 3e78 3c2f 7661 7269 6162 6c65 3e0a  le>x</variable>.
00000020: 2020 2020 2020 2020 0a20 2020 2020 2020          .       
00000030: 203c 6163 7469 6f6e 3e61 2027 273c 2f61   <action>a ''</a
00000040: 6374 696f 6e3e 0a0a                      ction>..
```
To reproduce you need to place the cursor on the first "a" of `<variable>` then press `j` `d` `d` to end up with
```xml

        <variable>x</action>
        <action>a ''</action>

```
Sorry for keeping you busy on this.

**Comment by andymass** [comment]
Thanks!  ef17dcb should do it, hopefully it is not too careful now to miss actually useful text changes.

> Could the plugin identify such cases?

I think it is likely possible with [text-properties](https://raw.githubusercontent.com/vim/vim/master/runtime/doc/textprop.txt), which is a new feature in vim 8.1.0694, but still being worked on.  However, if I go down this route, I won't be able to support old vim.

**Comment by step-** [comment]
This fix looks good here. Thank you!
